name: flutter_base_framework
description: A new Flutter package.
version: 0.0.1
homepage: https://github.com/hanlin19900610/flutter_base_framework.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # 日期格式化 https://pub.flutter-io.cn/packages/date_format
  date_format: ^2.0.2
  # 网络访问 https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.0
  # 路由, 状态管理, 依赖注入 https://pub.flutter-io.cn/packages/get
  get: ^4.1.1
  # https://pub.flutter-io.cn/packages/path
  path: ^1.8.0
  # https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^2.0.1
  # https://pub.flutter-io.cn/packages/flutter_easyrefresh
  flutter_easyrefresh: ^2.2.0
  # https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.0.5
  # 日历 https://pub.flutter-io.cn/packages/table_calendar
  table_calendar: ^3.0.0
  #下方两个为常用工具类 详见文档：https://github.com/Sky24n/common_utils
  #适配、sp本地缓存、路径util等
  # https://pub.flutter-io.cn/packages/flustars
  flustars: ^2.0.1
  #字符串util、日期格式化、加解密、日志、等等
  # https://pub.flutter-io.cn/packages/common_utils
  common_utils: ^2.0.2
  # 本地json对象存储
  # https://pub.flutter-io.cn/packages/localstorage
  localstorage: ^4.0.0+1
  # https://pub.flutter-io.cn/packages/device_info
  device_info: ^2.0.0
  # https://pub.flutter-io.cn/packages/package_info
  package_info: ^2.0.0
  # https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.0.3 #启动第三方app
  # https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^6.1.1
  # https://pub.flutter-io.cn/packages/flutter_image_compress 图片压缩
  flutter_image_compress: ^1.0.0
  # https://pub.flutter-io.cn/packages/webview_flutter
  webview_flutter: ^2.0.2
  # https://pub.flutter-io.cn/packages/extended_image
  extended_image: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
